project:
  type: "website"
  title: "PERCEPCION REMOTA"
  output-dir: _output
  render:
    - "index.qmd"
    - "2023/*.qmd"
    - "2023/sesiones/sesion01/*.qmd"
    - "2023/sesiones/sesion02/*.qmd"
    - "2023/sesiones/sesion03/*.qmd"
    - "2023/sesiones/sesion04/*.qmd"


website:
  title: "PERCEPCION REMOTA"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card: 
    creator: "@<twitter-handle>"
    site: "\\@<twitter-handle>"
  favicon: "figures/icons/STGEO.jpeg"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: 2023/index.qmd
        text: "ğŸ  Home"
      - href: 2023/syllabus.qmd
        text: "ğŸ““ Syllabus"
      # - href: 2023/communication.qmd
      #   text: "ğŸ“Ÿ Communication"
      # - href: 2023/assignments.qmd
      #   text: "âœï¸ Assignments"
      #   contents:
      #     - href: 2023/assignments/assignment01.qmd
      #       text: "ğŸ“ Assignment 01"
      #     - href: 2023/assignments/assignment02.qmd
      #       text: "ğŸ“ Assignment 02"
      #     - href: 2023/assignments/group_project.qmd
      #       text: "ğŸ‘¥ Group Project"
      - section: "ğŸ—“ï¸ Sesiones"
        contents:
         - href: 2023/sesiones/sesion01/page.qmd
           text: Sesion 01
           contents:
             - href: 2023/sesiones/sesion01/page.qmd
               text: ğŸ‘¨â€ğŸ« TeorÃ­a
             - href: 2023/sesiones/sesion01/lab.qmd
               text: ğŸ’» PrÃ¡ctica
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2023/sesiones/sesion02/page.qmd
           text: Sesion 02
           contents:
             - href: 2023/sesiones/sesion02/page.qmd
               text: ğŸ‘¨â€ğŸ« TeorÃ­a
             - href: 2023/sesiones/sesion02/lab.qmd
               text: ğŸ’» PrÃ¡ctica
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2023/sesiones/sesion03/page.qmd
           text: Sesion 03
           contents:
             - href: 2023/sesiones/sesion03/page.qmd
               text: ğŸ‘¨â€ğŸ« TeorÃ­a
             - href: 2023/sesiones/sesion03/lab.qmd
               text: ğŸ’» PrÃ¡ctica
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2023/sesiones/sesion04/page.qmd
           text: Sesion 04
           contents:
             - href: 2023/sesiones/sesion04/page.qmd
               text: ğŸ‘¨â€ğŸ« TeorÃ­a
             - href: 2023/sesiones/sesion04/lab.qmd
               text: ğŸ’» PrÃ¡ctica
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
  

  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2023, IALS" 



bibliography: references/references.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Ivan Lizarazo
    author-meta: Ivan Lizarazo
    date-format: "DD MMMM YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:ials\.github\.io\/|localhost)

    theme:
      light: 
        - journal
        - css/custom.scss # I use this just to change the default colour
    css: 
      - css/custom_style.css
      - css/syllabus.css
    toc: true

#margin-header: 
#![](/figures/icons/UNAL-1.png)

